ssconvert -S ../original_data_xls/Aberdeen.xls	 ../original_data_csv/Aberdeen.%s.csv
ssconvert -S ../original_data_xls/Alexandria.xls	 ../original_data_csv/Alexandria.%s.csv
ssconvert -S ../original_data_xls/Algiers.xls	 ../original_data_csv/Algiers.%s.csv
ssconvert -S ../original_data_xls/Angra.xls	 ../original_data_csv/Angra.%s.csv
ssconvert -S ../original_data_xls/Biskra.xls	 ../original_data_csv/Biskra.%s.csv
ssconvert -S ../original_data_xls/Brest.xls	 ../original_data_csv/Brest.%s.csv
ssconvert -S ../original_data_xls/DWR_stations.xls	 ../original_data_csv/DWR_stations.%s.csv
ssconvert -S ../original_data_xls/Funchal.xls	 ../original_data_csv/Funchal.%s.csv
ssconvert -S ../original_data_xls/Galway_in_ISPD.xls	 ../original_data_csv/Galway_in_ISPD.%s.csv
ssconvert -S ../original_data_xls/La_Coruna.xls	 ../original_data_csv/La_Coruna.%s.csv
ssconvert -S ../original_data_xls/Lesina_Split.xls	 ../original_data_csv/Lesina_Split.%s.csv
ssconvert -S ../original_data_xls/Lisbon.xls	 ../original_data_csv/Lisbon.%s.csv
ssconvert -S ../original_data_xls/London.xls	 ../original_data_csv/London.%s.csv
ssconvert -S ../original_data_xls/Lyons.xls	 ../original_data_csv/Lyons.%s.csv
ssconvert -S ../original_data_xls/ME_daily_pressure.xls	 ../original_data_csv/ME_daily_pressure.%s.csv
ssconvert -S ../original_data_xls/Mogador.xls	 ../original_data_csv/Mogador.%s.csv
ssconvert -S ../original_data_xls/Rochefort.xls	 ../original_data_csv/Rochefort.%s.csv
ssconvert -S ../original_data_xls/Rome.xls	 ../original_data_csv/Rome.%s.csv
ssconvert -S ../original_data_xls/Sibiu.xls	 ../original_data_csv/Sibiu.%s.csv
ssconvert -S ../original_data_xls/Stornaway.xls	 ../original_data_csv/Stornaway.%s.csv
ssconvert -S ../original_data_xls/Teneriffe.xls	 ../original_data_csv/Teneriffe.%s.csv
ssconvert -S ../original_data_xls/Toulon.xls	 ../original_data_csv/Toulon.%s.csv
ssconvert -S ../original_data_xls/Valentia.xls	 ../original_data_csv/Valentia.%s.csv
