ssconvert -S as_xlsx/scilly_pressure_ditigised1875.xlsx	as_csv/scilly_pressure_ditigised1875.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1876.xlsx	as_csv/scilly_pressure_ditigised1876.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1877.xlsx	as_csv/scilly_pressure_ditigised1877.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1878.xlsx	as_csv/scilly_pressure_ditigised1878.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1879.xlsx	as_csv/scilly_pressure_ditigised1879.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1880.xlsx	as_csv/scilly_pressure_ditigised1880.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1881.xlsx	as_csv/scilly_pressure_ditigised1881.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1882.xlsx	as_csv/scilly_pressure_ditigised1882.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1883.xlsx	as_csv/scilly_pressure_ditigised1883.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1884.xlsx	as_csv/scilly_pressure_ditigised1884.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1885.xlsx	as_csv/scilly_pressure_ditigised1885.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1886.xlsx	as_csv/scilly_pressure_ditigised1886.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1887.xlsx	as_csv/scilly_pressure_ditigised1887.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1888.xlsx	as_csv/scilly_pressure_ditigised1888.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1889.xlsx	as_csv/scilly_pressure_ditigised1889.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1890.xlsx	as_csv/scilly_pressure_ditigised1890.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1891.xlsx	as_csv/scilly_pressure_ditigised1891.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1892.xlsx	as_csv/scilly_pressure_ditigised1892.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1893.xlsx	as_csv/scilly_pressure_ditigised1893.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1894.xlsx	as_csv/scilly_pressure_ditigised1894.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1895.xlsx	as_csv/scilly_pressure_ditigised1895.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1896.xlsx	as_csv/scilly_pressure_ditigised1896.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1897.xlsx	as_csv/scilly_pressure_ditigised1897.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1898.xlsx	as_csv/scilly_pressure_ditigised1898.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1899.xlsx	as_csv/scilly_pressure_ditigised1899.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1900.xlsx	as_csv/scilly_pressure_ditigised1900.%s.csv
ssconvert -S as_xlsx/scilly_pressure_ditigised1901.xlsx	as_csv/scilly_pressure_ditigised1901.%s.csv
